name: Run unit test


on:
  push:
    branches: [main, gaction, action]
  pull_request:
    branches: [main, gaction, action]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v3
      - run: npm ci
      - run: npm test:all
